"""Public API of the deterministic fusion engine (dedup + attention).

Deterministic, replayable content deduplication (five documented levels,
zero physical deletion) and the mandatory-gates relevance ranking with
per-page attention budgets mirrored from ``manifests/relevance-policy.yaml``.
Pure domain code: no network, no clock, no persistence, no transactional
capability. Claude may summarize a cluster after this deterministic grouping;
it never decides that two contradictory facts are identical.
"""

from vertex_core.fusion.dedup import (
    CANONICAL_URL_WINDOW,
    FUSION_RULESET_VERSION,
    FusionInputError,
    FusionResult,
    RULE_CANONICAL_URL,
    RULE_FINGERPRINT,
    RULE_KEPT_DISTINCT,
    RULE_NATIVE_ID,
    RULE_SIMILARITY_FLAG,
    SIMILARITY_MIN_JACCARD_PERCENT,
    SIMILARITY_MIN_SHARED_ENTITIES,
    SIMILARITY_WINDOW,
    TRACKING_PARAM_PREFIXES,
    TRACKING_PARAMS,
    fuse,
    fusion_result_hash,
    normalize_canonical_url,
    normalize_title,
    title_fingerprint,
)
from vertex_core.fusion.models import (
    ContentCluster,
    ContentObservation,
    FusionAction,
    FusionDecision,
    SourceTier,
)
from vertex_core.fusion.relevance import (
    ATTENTION_BUDGETS,
    GATE_IDENTITY_OK,
    GATE_QUALITY_OK,
    GATE_RIGHTS_OK,
    GATE_SOURCE_OK,
    GATE_TIME_OK,
    GateEvaluation,
    PENALTY_CODES,
    POLICY_AUTHORITY,
    POLICY_VERSION,
    RankedItem,
    RelevanceInput,
    RelevanceInputError,
    RelevanceRanking,
    RelevanceRejection,
    RelevanceSubscores,
    REQUIRED_GATES,
    UNLIMITED,
    UnknownAttentionBudgetError,
    apply_attention_budget,
    evaluate_gates,
    rank_items,
)

__all__ = [
    # models
    "ContentCluster",
    "ContentObservation",
    "FusionAction",
    "FusionDecision",
    "SourceTier",
    # dedup
    "CANONICAL_URL_WINDOW",
    "FUSION_RULESET_VERSION",
    "FusionInputError",
    "FusionResult",
    "RULE_CANONICAL_URL",
    "RULE_FINGERPRINT",
    "RULE_KEPT_DISTINCT",
    "RULE_NATIVE_ID",
    "RULE_SIMILARITY_FLAG",
    "SIMILARITY_MIN_JACCARD_PERCENT",
    "SIMILARITY_MIN_SHARED_ENTITIES",
    "SIMILARITY_WINDOW",
    "TRACKING_PARAMS",
    "TRACKING_PARAM_PREFIXES",
    "fuse",
    "fusion_result_hash",
    "normalize_canonical_url",
    "normalize_title",
    "title_fingerprint",
    # relevance
    "ATTENTION_BUDGETS",
    "GATE_IDENTITY_OK",
    "GATE_QUALITY_OK",
    "GATE_RIGHTS_OK",
    "GATE_SOURCE_OK",
    "GATE_TIME_OK",
    "GateEvaluation",
    "PENALTY_CODES",
    "POLICY_AUTHORITY",
    "POLICY_VERSION",
    "RankedItem",
    "RelevanceInput",
    "RelevanceInputError",
    "RelevanceRanking",
    "RelevanceRejection",
    "RelevanceSubscores",
    "REQUIRED_GATES",
    "UNLIMITED",
    "UnknownAttentionBudgetError",
    "apply_attention_budget",
    "evaluate_gates",
    "rank_items",
]
